### ISSUE TITLE
Error using multi_easy_bin with --no-recluster

### ISSUE THREAD

**Issue by Ralwoss** [BigDataBiology/SemiBin#128]
Hi, 

I'm working with @bebatut on updating the Galaxy Wrapper for SemiBin. There was a problem using SemiBin multi_easy_bin with the parameter --no-recluster.
```
SemiBin multi_easy_bin \
--separator ':' \
--taxonomy-annotation-table test-data/taxonomy*.tsv \
--input-fasta test-data/input_multi.fasta.gz \
--input-bam test-data/input_multi*.bam \
--output 'output' \
--cannot-name 'cannot'  \
--ratio 0.05   \
--orf-finder 'fraggenescan' \
--random-seed 0 \
--epoches 20 \
--batch-size 2048 \
--max-node 1.0 \
--max-edges 200 \
--minfasta-kbs 200 \
--no-recluster
```
The error is :

```
Traceback (most recent call last):
  File "/home/ralwoss/anaconda3/envs/SemiBin/bin/SemiBin", line 10, in <module>
    sys.exit(main1())
             ^^^^^^^
  File "/home/ralwoss/anaconda3/envs/SemiBin/lib/python3.11/site-packages/SemiBin/main.py", line 1482, in main1
    main2(args, is_semibin2=False)
  File "/home/ralwoss/anaconda3/envs/SemiBin/lib/python3.11/site-packages/SemiBin/main.py", line 1468, in main2
    multi_easy_binning(
  File "/home/ralwoss/anaconda3/envs/SemiBin/lib/python3.11/site-packages/SemiBin/main.py", line 1270, in multi_easy_binning
    for bf in os.listdir(os.path.join(output, 'samples', sample, bin_dir_name)):
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: 'output/samples/S1/output_prerecluster_bins'
```
Without `--no-recluster` everything works. With `--no-recluster` there is no  `output/samples/S1/output_prerecluster_bins` directory, only an `output/samples/S1/output` directory.

It would be great if you could take a look

**Comment by psj1997** [comment]
Sorry for the late reply. I have fixed this issue. 

Thanks for more feedbacks from you.

Sincerely
Shaojun

**Comment by bebatut** [comment]
Thanks for fixing it.

Would it be possible to have a release with the fix so a new conda package will be available and can be used in Galaxy wrapper? Thanks

**Comment by luispedro** [comment]
We released a new version (`v1.5.1`). Conda sometimes takes a few hours for the auto-update to kick in, but it will be done later today or tomorrow. HTH, Luis

**Comment by luispedro** [comment]
Maybe their bot is better because it was actually immediate: https://github.com/bioconda/bioconda-recipes/pull/39775

Once those tests pass, it can be merged, so there will be a new conda version in an hour or so

**Comment by Ralwoss** [comment]
Hi,
this issue is back in SemiBin2.
multi_easy_bin --write-pre-reclustering-bins can not find the directory output_bins because there are output_pre_recluster_bins and output_after_recluster_bins instead of output_bins.

It would be great if you could take a look

**Comment by luispedro** [comment]
Thanks for the report, I can reproduce

**Comment by luispedro** [comment]
FYI, we released a new version (`2.0.2`) to fix this issue. At least this particular combination of arguments is now part of our test suite and future regressions will be caught

**Comment by Ralwoss** [comment]
Thanks a lot
